/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h>
#include <jemalloc/jemalloc.h>

/* Header for class offheap_jni_JemallocWrapper */

#ifndef _Included_offheap_jni_JemallocWrapper
#define _Included_offheap_jni_JemallocWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     offheap_jni_JemallocWrapper
 * Method:    malloc_0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_offheap_jni_JemallocWrapper_malloc_10
  (JNIEnv *, jclass, jlong);

/*
 * Class:     offheap_jni_JemallocWrapper
 * Method:    realloc_0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_offheap_jni_JemallocWrapper_realloc_10
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     offheap_jni_JemallocWrapper
 * Method:    free_0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_offheap_jni_JemallocWrapper_free_10
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
